"""inital commit

Revision ID: 40b505401d3f
Revises: 
Create Date: 2020-09-20 21:47:46.358301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b505401d3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('pitch_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('Pitch', sa.String(), nullable=True),
    sa.Column('Posting', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pitch_id')
    )
    op.create_table('profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('User_bio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('downvotes', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('reviews')
    op.drop_table('profiles')
    op.drop_table('pitches')
    # ### end Alembic commands ###
